const JSON_COMMA = ',',
      JSON_COLON = ':',
      JSON_LEFTBRACKET = '[',
      JSON_RIGHTBRACKET = ']',
      JSON_LEFTBRACE = '{',
      JSON_RIGHTBRACE = '}'

module.exports = {
    JSON_COMMA,
    JSON_COLON,
    JSON_LEFTBRACKET,
    JSON_RIGHTBRACKET,
    JSON_LEFTBRACE,
    JSON_RIGHTBRACE
}